doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_sqlsrv
                host:     172.16.2.4\MSSQLSERVER
                port:     1433
                dbname:   MegaCastings
                user:     megacasting
                password: Not24get
                charset:  UTF8 

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
