<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9uIOEeQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9uIOEeQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9uIOEeQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9uIOEeQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9uIOEeQ\App_KernelDevDebugContainer([
    'container.build_hash' => '9uIOEeQ',
    'container.build_id' => '0927ec06',
    'container.build_time' => 1607282167,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9uIOEeQ');
