<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGVcafTw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGVcafTw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGVcafTw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGVcafTw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGVcafTw\App_KernelDevDebugContainer([
    'container.build_hash' => 'GVcafTw',
    'container.build_id' => 'dba6ab6a',
    'container.build_time' => 1603457873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGVcafTw');
