<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIVY0CNg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIVY0CNg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIVY0CNg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIVY0CNg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIVY0CNg\App_KernelDevDebugContainer([
    'container.build_hash' => 'IVY0CNg',
    'container.build_id' => 'f4d57ca0',
    'container.build_time' => 1602144005,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIVY0CNg');
